console.log(`JS Operator`)
console.log(`TYpes of Operators`)
console.log(`Assignment Operator(==)`)
console.log(`Addition Operator(+)`)
console.log(`Subtration Operator(-)`)
console.log(`Multiplication Operator(*)`)
console.log(`Exponential Operator(**)`)
console.log(`Modulus Operator(%)`)
console.log(`Division Operator(/)`)
console.log(`Increment Operator(++)`)
console.log(`Decrement Operator(--)`)
console.log(`Greate Than Opertaor(>)`)
console.log(`Less Than Operator(<)`)
