console.log(`Loops are control structures`)
console.log(`Types of loops`)
console.log(`If condition`)
console.log(`if else condition`)
console.log(`if elseif else condition`)
console.log(`while loop`)
console.log(`do while loop`)
console.log(`switch case`)
console.log(`for loop`)
console.log(`forEach loop`)
